---
title: "rcausal"
author: "Chirayu Wongchokprasitti"
date: "June 23, 2016"
abstract: >
  This package is a R wrapper containing the Tetrad Library.
output: 
    BiocStyle::pdf_document
vignette: >
  %\VignetteIndexEntry{rcausal}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}  
---
# rcausal

R Wrapper for Tetrad Library, for more details see 
<https://github.com/bd2kccd/r-causal>.

## R Library Requirement
R >= 3.2.0, stringr, rJava, graph, RBGL, Rgraphviz

## Installation

### Install the R library requirements:

```{r}
### These packages should be available upon building due to DESCRIPTION imports clause.
#install.packages("stringr")
#install.packages("rJava")
## try http:// if https:// URLs are not supported
source("https://bioconductor.org/biocLite.R")
options(warn=-1)
if(! require("graph"))
   biocLite("graph")
if(! require("RBGL"))
  biocLite("RBGL")
if(! require("Rgraphviz"))
  biocLite("Rgraphviz") # For plotting graph
options(warn=1)
```

### Install the r-causal from github

```{r}
library(devtools)
#install_github("bd2kccd/r-causal")
require(rcausal)
```

## Example

```{r}
data("charity")    #Load the charity dataset
fgs <- fgs(df = charity, penaltydiscount = 2, maxDegree = -1, faithfulnessAssumed = TRUE,
            numOfThreads = 2, verbose = TRUE)    #Compute FGS search
fgs$parameters #Show the FGS's parameters
fgs$datasets #Show the dataset
fgs$nodes #Show the result's nodes
fgs$edges #Show the result's edges
library(Rgraphviz)
plot(fgs$graphNEL) #Plot the causal model
```
