---
title: "tetradR"
author: "Chirayu Wongchokprasitti"
date: "March 14, 2016"
output: pdf_document
---
# tetradR

R Wrapper for Tetrad Library, for more details see <https://github.com/bd2kccd/tetradR>.

## R Library Requirement
R >= 3.0.2, rJava, graph, RBGL, Rgraphviz

## Installation

### Install the R library requirements:

```{r}
install.packages("rJava")
## try http:// if https:// URLs are not supported
source("https://bioconductor.org/biocLite.R")
biocLite("graph")
biocLite("RBGL")
biocLite("Rgraphviz") # For plotting graph
```

### Install the release version of devtools from CRAN with

```{r}
install.packages("devtools")
```

### Install tetradR from github:

```{r}
library(devtools)
install_github("bd2kccd/tetradR")
```

## Example

```{r}
library(tetradR)
data("charity")   #Load the charity dataset
fgs <- fgs(df = charity, penaltydiscount = 2, depth = -1, faithfulness = TRUE, verbose = TRUE)    #Compute FGS search
fgs$parameters #Show the FGS's parameters
fgs$datasets #Show the dataset
fgs$nodes #Show the result's nodes
fgs$edges #Show the result's edges
library(Rgraphviz)
plot(fgs$graphNEL) #Plot the causal model
```
